allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@sanity/color-input@6.1.4'
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - esbuild
