/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ogImageAlt?: string;
  noIndex?: boolean;
};

export type ImageBlock = {
  _type: "imageBlock";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  secondImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  caption?: string;
  layout: "full" | "inset" | "pair";
};

export type TextBlock = {
  _type: "textBlock";
  heading?: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  layout?:
    "one-column" | "two-column-split" | "two-column-left" | "two-column-right";
};

export type KnowledgeBaseEntry = {
  _id: string;
  _type: "knowledgeBaseEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  tags?: Array<string>;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  headline: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  footerText?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  whatIDo?: Array<{
    title: string;
    description: string;
    _type: "serviceItem";
    _key: string;
  }>;
  resumeFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  email: string;
  howIWork?: Array<
    | ({
        _key: string;
      } & TextBlock)
    | ({
        _key: string;
      } & ImageBlock)
  >;
  socialLinks?: Array<{
    platform: string;
    url: string;
    _type: "socialLink";
    _key: string;
  }>;
  seo?: Seo;
  siteName?: string;
  titleTemplate?: string;
  defaultMetaDescription?: string;
  defaultOgImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company: string;
  companyUrl?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  order: number;
  roles: Array<{
    title: string;
    startDate: string;
    endDate?: string;
    summary?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "role";
    _key: string;
  }>;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  heroText?: string;
  headerBackgroundColor?: Color;
  headerForegroundColor?: Color;
  story?: Array<
    | ({
        _key: string;
      } & TextBlock)
    | ({
        _key: string;
      } & ImageBlock)
  >;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  coverPrimary?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  coverSecondary?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  coverMobile?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  coverLayout?: "left-dominant" | "right-dominant";
  techStack?: Array<string>;
  skills?: Array<
    | "state management"
    | "accessibility"
    | "data visualization"
    | "performance"
    | "backend/infra"
    | "design systems"
  >;
  impact?: Array<string>;
  role?: string;
  links?: Array<{
    label: string;
    url: string;
    _type: "link";
    _key: string;
  }>;
  featured?: boolean;
  order: number;
  dateCompleted?: string;
  seo?: Seo;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | ImageBlock
  | TextBlock
  | KnowledgeBaseEntry
  | SanityFileAssetReference
  | About
  | SanityImageCrop
  | SanityImageHotspot
  | Experience
  | Project
  | Color
  | Slug
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/sanity/queries.ts
// Variable: featuredProjectsQuery
// Query: *[_type == "project" && featured == true] | order(order asc) {    _id,    title,    slug,    summary,    coverPrimary {      ...,      "metadata": asset->metadata { lqip, dimensions }    },    coverSecondary {      ...,      "metadata": asset->metadata { lqip, dimensions }    },    coverMobile {      ...,      "metadata": asset->metadata { lqip, dimensions }    },    coverLayout,    order  }
export type FeaturedProjectsQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  summary: string;
  coverPrimary: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    metadata: {
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
  coverSecondary: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    metadata: {
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
  coverMobile: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    metadata: {
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
  coverLayout: "left-dominant" | "right-dominant" | null;
  order: number;
}>;

// Source: lib/sanity/queries.ts
// Variable: projectsQuery
// Query: *[_type == "project"] | order(order asc) {    _id,    title,    slug,    summary,    coverImage,    techStack,    skills,    impact,    role,    links,    featured,    order,    dateCompleted  }
export type ProjectsQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  summary: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  techStack: Array<string> | null;
  skills: Array<
    | "accessibility"
    | "backend/infra"
    | "data visualization"
    | "design systems"
    | "performance"
    | "state management"
  > | null;
  impact: Array<string> | null;
  role: string | null;
  links: Array<{
    label: string;
    url: string;
    _type: "link";
    _key: string;
  }> | null;
  featured: boolean | null;
  order: number;
  dateCompleted: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: otherProjectsQuery
// Query: *[_type == "project" && _id != $currentId] | order(order asc) [0...2] {    _id,    title,    slug,    summary,    coverImage {      ...,      "metadata": asset->metadata { lqip, dimensions }    },    order  }
export type OtherProjectsQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  summary: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    metadata: {
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
  order: number;
}>;

// Source: lib/sanity/queries.ts
// Variable: projectBySlugQuery
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    title,    slug,    summary,    heroText,    headerBackgroundColor,    headerForegroundColor,    story[] {      ...,      _type == "imageBlock" => {        ...,        image {          ...,          "metadata": asset->metadata { lqip, dimensions }        },        secondImage {          ...,          "metadata": asset->metadata { lqip, dimensions }        }      }    },    coverImage {      ...,      "metadata": asset->metadata { lqip, dimensions }    },    techStack,    skills,    impact,    role,    links,    featured,    order,    dateCompleted,    seo {      metaTitle,      metaDescription,      ogImage,      ogImageAlt,      noIndex    }  }
export type ProjectBySlugQueryResult = {
  _id: string;
  title: string;
  slug: Slug;
  summary: string;
  heroText: string | null;
  headerBackgroundColor: Color | null;
  headerForegroundColor: Color | null;
  story: Array<
    | {
        _key: string;
        _type: "imageBlock";
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        };
        secondImage: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        caption?: string;
        layout: "full" | "inset" | "pair";
      }
    | {
        _key: string;
        _type: "textBlock";
        heading?: string;
        content: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        layout?:
          | "one-column"
          | "two-column-left"
          | "two-column-right"
          | "two-column-split";
      }
  > | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    metadata: {
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
  techStack: Array<string> | null;
  skills: Array<
    | "accessibility"
    | "backend/infra"
    | "data visualization"
    | "design systems"
    | "performance"
    | "state management"
  > | null;
  impact: Array<string> | null;
  role: string | null;
  links: Array<{
    label: string;
    url: string;
    _type: "link";
    _key: string;
  }> | null;
  featured: boolean | null;
  order: number;
  dateCompleted: string | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    ogImageAlt: string | null;
    noIndex: boolean | null;
  } | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: projectsForIndexQuery
// Query: *[_type == "project"] {    _id,    title,    slug,    summary,    heroText,    role,    coverImage,    story,    techStack,    skills,    impact,    dateCompleted  }
export type ProjectsForIndexQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  summary: string;
  heroText: string | null;
  role: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  story: Array<
    | ({
        _key: string;
      } & ImageBlock)
    | ({
        _key: string;
      } & TextBlock)
  > | null;
  techStack: Array<string> | null;
  skills: Array<
    | "accessibility"
    | "backend/infra"
    | "data visualization"
    | "design systems"
    | "performance"
    | "state management"
  > | null;
  impact: Array<string> | null;
  dateCompleted: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: projectsForSitemapQuery
// Query: *[_type == "project"] | order(order asc) {    _id,    slug,    _updatedAt,    seo {      noIndex    }  }
export type ProjectsForSitemapQueryResult = Array<{
  _id: string;
  slug: Slug;
  _updatedAt: string;
  seo: {
    noIndex: boolean | null;
  } | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: projectForIndexByIdQuery
// Query: *[_type == "project" && _id == $id][0] {    _id,    title,    slug,    summary,    heroText,    role,    coverImage,    story,    techStack,    skills,    impact,    dateCompleted  }
export type ProjectForIndexByIdQueryResult = {
  _id: string;
  title: string;
  slug: Slug;
  summary: string;
  heroText: string | null;
  role: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  story: Array<
    | ({
        _key: string;
      } & ImageBlock)
    | ({
        _key: string;
      } & TextBlock)
  > | null;
  techStack: Array<string> | null;
  skills: Array<
    | "accessibility"
    | "backend/infra"
    | "data visualization"
    | "design systems"
    | "performance"
    | "state management"
  > | null;
  impact: Array<string> | null;
  dateCompleted: string | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: experienceQuery
// Query: *[_type == "experience"] | order(order asc) {    _id,    company,    companyUrl,    logo,    order,    roles[] {      _key,      title,      startDate,      endDate,      summary    }  }
export type ExperienceQueryResult = Array<{
  _id: string;
  company: string;
  companyUrl: string | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  order: number;
  roles: Array<{
    _key: string;
    title: string;
    startDate: string;
    endDate: string | null;
    summary: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }>;
}>;

// Source: lib/sanity/queries.ts
// Variable: experienceEntryByIdQuery
// Query: *[_type == "experience" && _id == $id][0] {    _id,    company,    companyUrl,    logo,    order,    roles[] {      _key,      title,      startDate,      endDate,      summary    }  }
export type ExperienceEntryByIdQueryResult = {
  _id: string;
  company: string;
  companyUrl: string | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  order: number;
  roles: Array<{
    _key: string;
    title: string;
    startDate: string;
    endDate: string | null;
    summary: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }>;
} | null;

// Source: lib/sanity/queries.ts
// Variable: knowledgeEntryByIdQuery
// Query: *[_type == "knowledgeBaseEntry" && _id == $id][0] {    _id,    title,    body,    tags  }
export type KnowledgeEntryByIdQueryResult = {
  _id: string;
  title: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  tags: Array<string> | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: knowledgeEntriesForIndexQuery
// Query: *[_type == "knowledgeBaseEntry"] {    _id,    title,    body,    tags  }
export type KnowledgeEntriesForIndexQueryResult = Array<{
  _id: string;
  title: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  tags: Array<string> | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: aboutForSitemapQuery
// Query: *[_type == "about"][0] {    _updatedAt  }
export type AboutForSitemapQueryResult = {
  _updatedAt: string;
} | null;

// Source: lib/sanity/queries.ts
// Variable: aboutQuery
// Query: *[_type == "about"][0] {    _id,    name,    headline,    bio,    whatIDo[] {      _key,      title,      description    },    logo,    footerText,    "resumeUrl": resumeFile.asset->url,    email,    socialLinks,    howIWork[] {      ...,      _type == "imageBlock" => {        ...,        image {          ...,          "metadata": asset->metadata { lqip, dimensions }        },        secondImage {          ...,          "metadata": asset->metadata { lqip, dimensions }        }      }    },    seo {      metaTitle,      metaDescription,      ogImage,      ogImageAlt,      noIndex    },    siteName,    titleTemplate,    defaultMetaDescription,    defaultOgImage  }
export type AboutQueryResult = {
  _id: string;
  name: string;
  headline: string;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  whatIDo: Array<{
    _key: string;
    title: string;
    description: string;
  }> | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  footerText: string | null;
  resumeUrl: string | null;
  email: string;
  socialLinks: Array<{
    platform: string;
    url: string;
    _type: "socialLink";
    _key: string;
  }> | null;
  howIWork: Array<
    | {
        _key: string;
        _type: "imageBlock";
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        };
        secondImage: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        caption?: string;
        layout: "full" | "inset" | "pair";
      }
    | {
        _key: string;
        _type: "textBlock";
        heading?: string;
        content: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        layout?:
          | "one-column"
          | "two-column-left"
          | "two-column-right"
          | "two-column-split";
      }
  > | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    ogImageAlt: string | null;
    noIndex: boolean | null;
  } | null;
  siteName: string | null;
  titleTemplate: string | null;
  defaultMetaDescription: string | null;
  defaultOgImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "project" && featured == true] | order(order asc) {\n    _id,\n    title,\n    slug,\n    summary,\n    coverPrimary {\n      ...,\n      "metadata": asset->metadata { lqip, dimensions }\n    },\n    coverSecondary {\n      ...,\n      "metadata": asset->metadata { lqip, dimensions }\n    },\n    coverMobile {\n      ...,\n      "metadata": asset->metadata { lqip, dimensions }\n    },\n    coverLayout,\n    order\n  }\n': FeaturedProjectsQueryResult;
    '\n  *[_type == "project"] | order(order asc) {\n    _id,\n    title,\n    slug,\n    summary,\n    coverImage,\n    techStack,\n    skills,\n    impact,\n    role,\n    links,\n    featured,\n    order,\n    dateCompleted\n  }\n': ProjectsQueryResult;
    '\n  *[_type == "project" && _id != $currentId] | order(order asc) [0...2] {\n    _id,\n    title,\n    slug,\n    summary,\n    coverImage {\n      ...,\n      "metadata": asset->metadata { lqip, dimensions }\n    },\n    order\n  }\n': OtherProjectsQueryResult;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    summary,\n    heroText,\n    headerBackgroundColor,\n    headerForegroundColor,\n    story[] {\n      ...,\n      _type == "imageBlock" => {\n        ...,\n        image {\n          ...,\n          "metadata": asset->metadata { lqip, dimensions }\n        },\n        secondImage {\n          ...,\n          "metadata": asset->metadata { lqip, dimensions }\n        }\n      }\n    },\n    coverImage {\n      ...,\n      "metadata": asset->metadata { lqip, dimensions }\n    },\n    techStack,\n    skills,\n    impact,\n    role,\n    links,\n    featured,\n    order,\n    dateCompleted,\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage,\n      ogImageAlt,\n      noIndex\n    }\n  }\n': ProjectBySlugQueryResult;
    '\n  *[_type == "project"] {\n    _id,\n    title,\n    slug,\n    summary,\n    heroText,\n    role,\n    coverImage,\n    story,\n    techStack,\n    skills,\n    impact,\n    dateCompleted\n  }\n': ProjectsForIndexQueryResult;
    '\n  *[_type == "project"] | order(order asc) {\n    _id,\n    slug,\n    _updatedAt,\n    seo {\n      noIndex\n    }\n  }\n': ProjectsForSitemapQueryResult;
    '\n  *[_type == "project" && _id == $id][0] {\n    _id,\n    title,\n    slug,\n    summary,\n    heroText,\n    role,\n    coverImage,\n    story,\n    techStack,\n    skills,\n    impact,\n    dateCompleted\n  }\n': ProjectForIndexByIdQueryResult;
    '\n  *[_type == "experience"] | order(order asc) {\n    _id,\n    company,\n    companyUrl,\n    logo,\n    order,\n    roles[] {\n      _key,\n      title,\n      startDate,\n      endDate,\n      summary\n    }\n  }\n': ExperienceQueryResult;
    '\n  *[_type == "experience" && _id == $id][0] {\n    _id,\n    company,\n    companyUrl,\n    logo,\n    order,\n    roles[] {\n      _key,\n      title,\n      startDate,\n      endDate,\n      summary\n    }\n  }\n': ExperienceEntryByIdQueryResult;
    '\n  *[_type == "knowledgeBaseEntry" && _id == $id][0] {\n    _id,\n    title,\n    body,\n    tags\n  }\n': KnowledgeEntryByIdQueryResult;
    '\n  *[_type == "knowledgeBaseEntry"] {\n    _id,\n    title,\n    body,\n    tags\n  }\n': KnowledgeEntriesForIndexQueryResult;
    '\n  *[_type == "about"][0] {\n    _updatedAt\n  }\n': AboutForSitemapQueryResult;
    '\n  *[_type == "about"][0] {\n    _id,\n    name,\n    headline,\n    bio,\n    whatIDo[] {\n      _key,\n      title,\n      description\n    },\n    logo,\n    footerText,\n    "resumeUrl": resumeFile.asset->url,\n    email,\n    socialLinks,\n    howIWork[] {\n      ...,\n      _type == "imageBlock" => {\n        ...,\n        image {\n          ...,\n          "metadata": asset->metadata { lqip, dimensions }\n        },\n        secondImage {\n          ...,\n          "metadata": asset->metadata { lqip, dimensions }\n        }\n      }\n    },\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage,\n      ogImageAlt,\n      noIndex\n    },\n    siteName,\n    titleTemplate,\n    defaultMetaDescription,\n    defaultOgImage\n  }\n': AboutQueryResult;
  }
}
