/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageBlock = {
  _type: "imageBlock";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  secondImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  caption?: string;
  layout: "full" | "inset" | "pair";
};

export type TextBlock = {
  _type: "textBlock";
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  headline: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  availabilityStatus?: string;
  footerMessage?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  resumeFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  email: string;
  socialLinks?: Array<{
    platform: string;
    url: string;
    _type: "socialLink";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company: string;
  title: string;
  startDate: string;
  endDate?: string;
  summary?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  order: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  heroText?: string;
  story?: Array<
    | ({
        _key: string;
      } & TextBlock)
    | ({
        _key: string;
      } & ImageBlock)
  >;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  coverPrimary?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  coverSecondary?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  coverMobile?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  coverLayout?: "left-dominant" | "right-dominant";
  techStack?: Array<string>;
  skills?: Array<
    | "state management"
    | "accessibility"
    | "data visualization"
    | "performance"
    | "backend/infra"
    | "design systems"
  >;
  impact?: Array<string>;
  role?: string;
  links?: Array<{
    label: string;
    url: string;
    _type: "link";
    _key: string;
  }>;
  featured?: boolean;
  order: number;
  dateCompleted?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ImageBlock
  | TextBlock
  | SanityFileAssetReference
  | About
  | SanityImageCrop
  | SanityImageHotspot
  | Experience
  | Project
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/sanity/queries.ts
// Variable: featuredProjectsQuery
// Query: *[_type == "project" && featured == true] | order(order asc) {    _id,    title,    slug,    summary,    coverPrimary,    coverSecondary,    coverMobile,    coverLayout,    order  }
export type FeaturedProjectsQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  summary: string;
  coverPrimary: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  coverSecondary: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  coverMobile: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  coverLayout: "left-dominant" | "right-dominant" | null;
  order: number;
}>;

// Source: lib/sanity/queries.ts
// Variable: projectsQuery
// Query: *[_type == "project"] | order(order asc) {    _id,    title,    slug,    summary,    coverImage,    techStack,    skills,    impact,    role,    links,    featured,    order,    dateCompleted  }
export type ProjectsQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  summary: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  techStack: Array<string> | null;
  skills: Array<
    | "accessibility"
    | "backend/infra"
    | "data visualization"
    | "design systems"
    | "performance"
    | "state management"
  > | null;
  impact: Array<string> | null;
  role: string | null;
  links: Array<{
    label: string;
    url: string;
    _type: "link";
    _key: string;
  }> | null;
  featured: boolean | null;
  order: number;
  dateCompleted: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: projectBySlugQuery
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    title,    slug,    summary,    heroText,    story,    coverImage,    techStack,    skills,    impact,    role,    links,    featured,    order,    dateCompleted  }
export type ProjectBySlugQueryResult = {
  _id: string;
  title: string;
  slug: Slug;
  summary: string;
  heroText: string | null;
  story: Array<
    | ({
        _key: string;
      } & ImageBlock)
    | ({
        _key: string;
      } & TextBlock)
  > | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  techStack: Array<string> | null;
  skills: Array<
    | "accessibility"
    | "backend/infra"
    | "data visualization"
    | "design systems"
    | "performance"
    | "state management"
  > | null;
  impact: Array<string> | null;
  role: string | null;
  links: Array<{
    label: string;
    url: string;
    _type: "link";
    _key: string;
  }> | null;
  featured: boolean | null;
  order: number;
  dateCompleted: string | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: projectsForIndexQuery
// Query: *[_type == "project"] {    _id,    title,    slug,    summary,    story,    techStack,    skills,    impact,    dateCompleted  }
export type ProjectsForIndexQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  summary: string;
  story: Array<
    | ({
        _key: string;
      } & ImageBlock)
    | ({
        _key: string;
      } & TextBlock)
  > | null;
  techStack: Array<string> | null;
  skills: Array<
    | "accessibility"
    | "backend/infra"
    | "data visualization"
    | "design systems"
    | "performance"
    | "state management"
  > | null;
  impact: Array<string> | null;
  dateCompleted: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: projectForIndexByIdQuery
// Query: *[_type == "project" && _id == $id][0] {    _id,    title,    slug,    summary,    story,    techStack,    skills,    impact,    dateCompleted  }
export type ProjectForIndexByIdQueryResult = {
  _id: string;
  title: string;
  slug: Slug;
  summary: string;
  story: Array<
    | ({
        _key: string;
      } & ImageBlock)
    | ({
        _key: string;
      } & TextBlock)
  > | null;
  techStack: Array<string> | null;
  skills: Array<
    | "accessibility"
    | "backend/infra"
    | "data visualization"
    | "design systems"
    | "performance"
    | "state management"
  > | null;
  impact: Array<string> | null;
  dateCompleted: string | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: experienceQuery
// Query: *[_type == "experience"] | order(order asc) {    _id,    company,    title,    startDate,    endDate,    summary,    logo,    order  }
export type ExperienceQueryResult = Array<{
  _id: string;
  company: string;
  title: string;
  startDate: string;
  endDate: string | null;
  summary: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  order: number;
}>;

// Source: lib/sanity/queries.ts
// Variable: experienceEntryByIdQuery
// Query: *[_type == "experience" && _id == $id][0] {    _id,    company,    title,    startDate,    endDate,    summary,    logo,    order  }
export type ExperienceEntryByIdQueryResult = {
  _id: string;
  company: string;
  title: string;
  startDate: string;
  endDate: string | null;
  summary: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  order: number;
} | null;

// Source: lib/sanity/queries.ts
// Variable: aboutQuery
// Query: *[_type == "about"][0] {    _id,    name,    headline,    bio,    logo,    availabilityStatus,    footerMessage,    "resumeUrl": resumeFile.asset->url,    email,    socialLinks  }
export type AboutQueryResult = {
  _id: string;
  name: string;
  headline: string;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  availabilityStatus: string | null;
  footerMessage: string | null;
  resumeUrl: string | null;
  email: string;
  socialLinks: Array<{
    platform: string;
    url: string;
    _type: "socialLink";
    _key: string;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "project" && featured == true] | order(order asc) {\n    _id,\n    title,\n    slug,\n    summary,\n    coverPrimary,\n    coverSecondary,\n    coverMobile,\n    coverLayout,\n    order\n  }\n': FeaturedProjectsQueryResult;
    '\n  *[_type == "project"] | order(order asc) {\n    _id,\n    title,\n    slug,\n    summary,\n    coverImage,\n    techStack,\n    skills,\n    impact,\n    role,\n    links,\n    featured,\n    order,\n    dateCompleted\n  }\n': ProjectsQueryResult;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    summary,\n    heroText,\n    story,\n    coverImage,\n    techStack,\n    skills,\n    impact,\n    role,\n    links,\n    featured,\n    order,\n    dateCompleted\n  }\n': ProjectBySlugQueryResult;
    '\n  *[_type == "project"] {\n    _id,\n    title,\n    slug,\n    summary,\n    story,\n    techStack,\n    skills,\n    impact,\n    dateCompleted\n  }\n': ProjectsForIndexQueryResult;
    '\n  *[_type == "project" && _id == $id][0] {\n    _id,\n    title,\n    slug,\n    summary,\n    story,\n    techStack,\n    skills,\n    impact,\n    dateCompleted\n  }\n': ProjectForIndexByIdQueryResult;
    '\n  *[_type == "experience"] | order(order asc) {\n    _id,\n    company,\n    title,\n    startDate,\n    endDate,\n    summary,\n    logo,\n    order\n  }\n': ExperienceQueryResult;
    '\n  *[_type == "experience" && _id == $id][0] {\n    _id,\n    company,\n    title,\n    startDate,\n    endDate,\n    summary,\n    logo,\n    order\n  }\n': ExperienceEntryByIdQueryResult;
    '\n  *[_type == "about"][0] {\n    _id,\n    name,\n    headline,\n    bio,\n    logo,\n    availabilityStatus,\n    footerMessage,\n    "resumeUrl": resumeFile.asset->url,\n    email,\n    socialLinks\n  }\n': AboutQueryResult;
  }
}
